In [19]:
import pandas as pd
import numpy as np
import cv2
import sklearn
import os
import matplotlib.pyplot as plt
from collections import Counter

In [8]:
train_directory = "Dataset/train"
validation_directory = "Dataset/valid"

In [27]:
def cargar_imagenes_y_etiquetas(directorio):
    imagenes = []
    etiquetas = []
    for root, _, files in os.walk(directorio):
        for file in files:
            # Verificar si el archivo es una imagen (puedes ajustar esta condición según el formato de tus imágenes)
            if file.endswith(".jpg") or file.endswith(".png") or file.endswith(".jpeg"):
                # Obtener la ruta completa de la imagen
                imagen_path = os.path.join(root, file)
                # El nombre del directorio padre es la etiqueta (Y)
                etiqueta = os.path.basename(root)
                # Cargar la imagen
                imagen = cv2.imread(imagen_path)  # Utiliza la biblioteca que prefieras para cargar la imagen
                # Agregar la imagen y su etiqueta a las listas correspondientes
                imagenes.append(imagen)
                etiquetas.append(etiqueta)
    return imagenes, etiquetas


X_train, y_train = cargar_imagenes_y_etiquetas(train_directory)

X_val, y_val = cargar_imagenes_y_etiquetas(validation_directory)


print("Ejemplos de imágenes y etiquetas de entrenamiento:")
for imagen, etiqueta in zip(X_train[:5], y_train[:5]): 
    print(f"Imagen: {imagen}, Etiqueta: {etiqueta}")

print("\nEjemplos de imágenes y etiquetas de validación:")
for imagen, etiqueta in zip(X_val[:5], y_val[:5]): 
    print(f"Imagen: {imagen}, Etiqueta: {etiqueta}")

Ejemplos de imágenes y etiquetas de entrenamiento:
Imagen: [[[ 34  48  67]
  [ 36  50  69]
  [ 38  52  71]
  ...
  [ 36  45  59]
  [ 36  45  59]
  [ 36  45  59]]

 [[ 33  47  66]
  [ 35  49  68]
  [ 37  51  70]
  ...
  [ 36  45  59]
  [ 36  45  59]
  [ 36  45  59]]

 [[ 33  47  66]
  [ 35  49  68]
  [ 37  51  70]
  ...
  [ 36  45  59]
  [ 36  45  59]
  [ 36  45  59]]

 ...

 [[ 41  76  26]
  [ 42  78  26]
  [ 43  79  25]
  ...
  [151 170  77]
  [150 169  76]
  [150 169  76]]

 [[ 47  84  28]
  [ 48  86  28]
  [ 49  87  27]
  ...
  [147 166  73]
  [146 165  72]
  [146 165  72]]

 [[ 46  84  24]
  [ 47  86  24]
  [ 48  87  25]
  ...
  [145 164  71]
  [144 163  70]
  [143 162  69]]], Etiqueta: 88 AN
Imagen: [[[ 2  1  3]
  [ 0  0  1]
  [ 2  0  4]
  ...
  [42 80 38]
  [43 74 35]
  [ 0 23  0]]

 [[ 1  0  2]
  [ 0  0  1]
  [ 2  0  4]
  ...
  [43 80 40]
  [43 74 37]
  [ 0 21  0]]

 [[ 0  0  1]
  [ 0  0  1]
  [ 3  0  5]
  ...
  [42 78 42]
  [42 71 38]
  [ 0 18  0]]

 ...

 [[ 0  0  0]
  [ 0  0 

In [29]:
def contar_imagenes_por_clase(etiquetas):
    conteo = Counter(etiquetas)
    return conteo

# Calcular el recuento de imágenes por clase en el conjunto de entrenamiento y validación
count_train = contar_imagenes_por_clase(y_train)
count_validation = contar_imagenes_por_clase(y_val)

df_count_train = pd.DataFrame(list(count_train.items()), columns=['Clase', 'Total de imágenes'])
df_count_validation = pd.DataFrame(list(count_validation.items()), columns=['Clase', 'Total de imágenes'])

df_count_train.to_excel('Recursos/Recuentro Entrenamiento.xlsx', index=False)
df_count_validation.to_excel('Recursos/Recuento Validación.xlsx', index=False)

Revisando manualmente los datos en excel, me encuentro conque la clase menos popular es la crimson patch, con 96 imágenes. Y la clase más popular tiene 184 imágenes, esta corresponde a Cloak Mourning, tendremos en cuenta estos puntos para la revisión de las métricas del modelo, y ver cómo predice cada una.